export const quiz = {
	topic: 'Capital of countries',
	level: 'Beginner',
	totalQuestions: 20,
	perQuestionScore: 1,
	questions: [
		{
			key: 1,
			question: 'What is the capital of Peru?',
			choices: ['Santiago', 'Caracas', 'Santo Domingo', 'Bogotá', 'Lima'],
			type: 'MCQs',
			correctAnswer: 'Lima',
		},
		{
			key: 2,
			question: 'What is the capital of Nicaragua?',
			choices: ['Managua', 'Ontario', 'Canberra', 'Washington. D.C.', 'Quito'],
			type: 'MCQs',
			correctAnswer: 'Managua',
		},
		{
			key: 3,
			question: 'What is the capital of Guatemala?',
			choices: ['Santiago', 'Dublin', 'Hanoi', 'Guatemala City', 'Cairo'],
			type: 'MCQs',
			correctAnswer: 'Guatemala City',
		},
		{
			key: 4,
			question: 'What is the capital of Argentina?',
			choices: ['Budapest', 'Brasilia', 'Buenos Aires', 'Pretoria', 'Berlin'],
			type: 'MCQs',
			correctAnswer: 'Buenos Aires',
		},
		{
			key: 5,
			question: 'What is the capital of China?',
			choices: ['Baghdad', 'Baku', 'Bamako', 'Astana', 'Beijing'],
			type: 'MCQs',
			correctAnswer: 'Beijing',
		},
		{
			key: 6,
			question: 'What is the capital of Nigeria?',
			choices: ['Abuja', 'Amsterdam', 'Ankara', 'Abu Dahbi', 'Amman'],
			type: 'MCQs',
			correctAnswer: 'Abuja',
		},
		{
			key: 7,
			question: 'What is the capital of Madagascar?',
			choices: ['Apia', 'Astana', 'Accra', 'Antananarivo', 'Aden'],
			type: 'MCQs',
			correctAnswer: 'Antananarivo',
		},
		{
			key: 8,
			question: 'What is the capital of Paraguay?',
			choices: ['Bangui', 'Asunción', 'Alofi', 'Bern', 'Brades'],
			type: 'MCQs',
			correctAnswer: 'Asunción',
		},
		{
			key: 9,
			question: 'What is the capital of Greece?',
			choices: ['Brussels', 'Cape Town', 'Paris', 'Athens', 'Bissau'],
			type: 'MCQs',
			correctAnswer: 'Athens',
		},
		{
			key: 10,
			question: 'What is the capital of Denmark?',
			choices: ['Douglas', 'Cotonou', 'Conakry', 'Dodoma', 'Copenhagen'],
			type: 'MCQs',
			correctAnswer: 'Copenhagen',
		},
		{
			key: 11,
			question: 'What is the capital of Cuba?',
			choices: ['Caracas', 'Lima', 'Lisbon', 'Hamilton', 'Havana'],
			type: 'MCQs',
			correctAnswer: 'Havana',
		},
		{
			key: 12,
			question: 'What is the capital of Ukraine?',
			choices: ['Kyiv', 'Ottawa', 'Pago Pago', 'La Paz', 'Sucre'],
			type: 'MCQs',
			correctAnswer: 'Kyiv',
		},
		{
			key: 13,
			question: 'What is the capital of Aruba?',
			choices: ['Port Louis', 'Paris', 'Oslo', 'Nicosia', 'Oranjestad'],
			type: 'MCQs',
			correctAnswer: 'Oranjestad',
		},
		{
			key: 14,
			question: 'What is the capital of Dominica?',
			choices: ['San José', 'Roseau', 'Rome', 'San Marino', 'San Salvador'],
			type: 'MCQs',
			correctAnswer: 'Roseau',
		},
		{
			key: 15,
			question: 'What is the capital of Fiji?',
			choices: ['Tiapei', 'Stanley', 'Suva', 'Skopje', "St. George's"],
			type: 'MCQs',
			correctAnswer: 'Roseau',
		},
		{
			key: 16,
			question: 'What is the capital of Iran?',
			choices: ['Tiraspol', 'Tirana', 'Taipei', 'Teheran', 'Tokyo'],
			type: 'MCQs',
			correctAnswer: 'Teheran',
		},
		{
			key: 17,
			question: 'What is the capital of Croatia?',
			choices: ['Wellington', 'Zagreb', 'Vienna', 'Vaduz', 'Tunis'],
			type: 'MCQs',
			correctAnswer: 'Zagreb',
		},
		{
			key: 18,
			question: 'What is the capital of Cameroon?',
			choices: ['Yaoundé', 'Willemstand', 'Victoria', 'Vilnius', 'Ulaanbaatar'],
			type: 'MCQs',
			correctAnswer: 'Willemstand',
		},
		{
			key: 19,
			question: 'What is the capital of Poland?',
			choices: ['Valleta', 'Tirana', 'Seoul', 'Sarajevo', 'Warsaw'],
			type: 'MCQs',
			correctAnswer: 'Warsaw',
		},
		{
			key: 20,
			question: 'What is the capital of North Korea?',
			choices: ['Seoul', 'Rabat', 'Pyongyang', 'Kingstown', 'Kigali'],
			type: 'MCQs',
			correctAnswer: 'Pyongyang',
		},
	],
}
